# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [pull_request]

jobs:
  # Linting
  linting:
    runs-on: ubuntu-latest
    steps:
    - name: Python Style Checker
      uses: andymckay/pycodestyle-action@0.1.3

